BlogMVCBoost/Controllers/ArticleController.cs
using BlogMVCBoost.Context;
using BlogMVCBoost.Models;
using BlogMVCBoost.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Runtime.CompilerServices;

namespace BlogMVCBoost.Controllers
{
    public class ArticleController : Controller
    {
        BoostBlogDbContext _db;
        private readonly UserManager<AppUser> _userManager;
        private readonly IPasswordHasher<AppUser> _passwordHasher;

        public ArticleController(UserManager<AppUser> userManager, IPasswordHasher<AppUser> passwordHasher, BoostBlogDbContext db)
        {
            _userManager = userManager;
            _passwordHasher = passwordHasher;
            _db = db;
        }
        public IActionResult Write()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Write(ArticleVM a)
        {
            AppUser user = await _userManager.FindByNameAsync(User.Identity.Name);
            Article article = new Article()
            {
                AppUserID = user.Id,
                ArticleName = a.ArticleName,
                ArticleBody = a.ArticleBody,
                ArticleImage = a.ArticleImage
            };
            _db.Articles.Add(article);
            _db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
        public async Task<IActionResult> MyArticleList()
        {
            AppUser user = await _userManager.FindByNameAsync(User.Identity.Name);
            return View(_db.Articles.ToList().Where(u => u.AppUserID == user.Id));
        }

        public IActionResult UpdateArticle(int id)
        {
            var article = _db.Articles.FirstOrDefault(x => x.ArticleID == id);
            ArticleVM articleVM = new ArticleVM()
            {
                ArticleBody=article.ArticleBody,
                ArticleImage=article.ArticleImage,
                ArticleName = article.ArticleName,
            };
            if (article == null) { return NotFound(); }
            return View(articleVM);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateArticle(int id, ArticleVM p)
        {
            var article = _db.Articles.Find(id);
            article.ArticleName = p.ArticleName;
            article.ArticleBody = p.ArticleBody;
            article.ArticleImage = p.ArticleImage;
            article.UpdatedTime = DateTime.Parse(DateTime.Now.ToString("dd-MMM-yyyy"));
            _db.Articles.Update(article);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> DeleteArticle(int id)
        {
            var article = _db.Articles.Find(id);
            _db.Remove(article);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }
        public IActionResult ReadArticle(int id)
        {
            ArticleUserVM articleUserVM = new ArticleUserVM()
            {
                Article = _db.Articles.Find(id)
            };            
            return View(articleUserVM);
        }
    }
}

BlogMVCBoost/Controllers/ProfileController.cs
using BlogMVCBoost.DTOs;
using BlogMVCBoost.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BlogMVCBoost.Controllers
{
    public class ProfileController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly IPasswordHasher<AppUser> _passwordHasher;

        public ProfileController(UserManager<AppUser> userManager, IPasswordHasher<AppUser> passwordHasher)
        {
            _userManager = userManager;
            _passwordHasher = passwordHasher;
        }

        public async Task<IActionResult> ProfilePage()
        {
            string name = User.Identity.Name;
            AppUser user = await _userManager.FindByNameAsync(name);

            if (user != null)
            {
                UserUpdateDTO userUpdateDTO = new UserUpdateDTO()
                {
                    Name=user.Name,
                    Surname=user.Surname,
                    Username = user.UserName,
                    Email = user.Email,
                };
                return View(userUpdateDTO);
            }
            else
                return RedirectToAction("ProfilePage");
        }

        [HttpPost]
        public async Task<IActionResult> ProfilePage(UserUpdateDTO userUpdateDTO)
        {
            if (ModelState.IsValid)
            {
                AppUser user = await _userManager.FindByNameAsync(userUpdateDTO.Username);
                user.UserName = userUpdateDTO.Username;
                user.Email = userUpdateDTO.Email;
                user.Name = userUpdateDTO.Name;
                user.Surname= userUpdateDTO.Surname;

                if (userUpdateDTO.Password != null)
                    user.PasswordHash = _passwordHasher.HashPassword(user, userUpdateDTO.Password);

                IdentityResult result = await _userManager.UpdateAsync(user);

                if (result.Succeeded)
                    return RedirectToAction("ProfilePage");
                else
                    Errors(result);
            }

            return View(userUpdateDTO);
        }
        private void Errors(IdentityResult result)
        {
            foreach (IdentityError error in result.Errors)
            {
                TempData["Error"] = $"{error.Code} - {error.Description}";
            }
        }

    }


}

BlogMVCBoost/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogMVCBoost</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BlogMVCBoost.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BlogMVCBoost</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Profile" asp-action="ProfilePage">Profile</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Article" asp-action="Write">Write</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Article" asp-action="MyArticleList">My Articles</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Login" asp-action="Logout">Logout</a>
                            </li>

                        }
                        else
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Home" asp-action="About">About</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Login" asp-action="SignUp">SignUp</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Login" asp-action="SignIn">SignIn</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BlogMVCBoost - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>